### ISSUE TITLE
New requirement - at least one minus letter validation

### ISSUE THREAD

**Issue by usackoka** [sators/react-password-checklist#7] opened 2021-07-20 19:26 UTC
Thanks

**Comment by sators** [comment] 2021-07-20 20:31
Just to clarify here @usackoka - are you suggesting that requiring a lowercase letter should be a validation option?

**Comment by usackoka** [comment] 2021-07-20 20:38
Yes, for example:

<PasswordChecklist
        rules={['length', 'specialChar', 'number', 'capital', 'match', 'minus']}
        messages={{
                        minus: 'At least one lower case letter.',


is that posible?

**Comment by sators** [comment] 2021-07-20 20:50
Duplicate of #6

**Closed as completed by sators** 2021-07-20 20:50 UTC
Labels: duplicate
